version: '3.8'

services:
  spring-blue:
    image: ${DOCKER_USERNAME}/spring-app:latest
    container_name: spring-blue
    ports:
      - "8081:8080"  # 내부 8080, 외부 8081로 매핑
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - custom-network

  spring-green:
    image: ${DOCKER_USERNAME}/spring-app:latest
    container_name: spring-green
    ports:
      - "8082:8080"  # 내부 8080, 외부 8082로 매핑
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - custom-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge

volumes:
  db-data:
