name: Deploy

on:
  push:
    branches:
      main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH 서버 접속
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_YML }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: APPLICATION_YML
          script_stop: true
          script: |
            cd /home/ubuntu/cicd-practice
            rm -rf src/main/resources/application.yml
            git pull origin main
            echo "$APPLICATION_YML" > src/main/resources/application.yml
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 & 
