name: Deploy

on:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      active_port: ${{ steps.run-deploy-scripts.outputs.active_port }} # 새로운 컨테이너의 포트

    steps:
      - name: Github Repository 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: Gradle 테스트 및 빌드
        run: ./gradlew clean build -x test

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub 이미지 빌드 및 푸시
        run: |
          docker build --platform=linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/spring-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    outputs:
      next_port: ${{ steps.run-deploy-scripts.outputs.next_port }} # 아래 스텝 ID를 참조합니다.

    steps:
      - name: "레포지토리 체크아웃"
        uses: actions/checkout@v4

      - name: "docker-compose.yml SCP 전송"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./docker-compose.yml"
          target: "~/cicd-practice/"

      - name: "무중단 배포 관련 스크립트 SCP 전송"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: ".github/workflows/scripts/*.sh"
          target: "~/cicd-practice/"

      - name: "애플리케이션 서버 구동"
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            set -e
            cd ~/cicd-practice/.github/workflows/scripts
            chmod +x *.sh
            
            ./switch-port.sh && \
            source .deploy-info.env && \
            ./start-next-container.sh && \
            ./health-check.sh && \
            ./stop-prev-container.sh && \
            
            echo "active_port=$NEXT_PORT" >> $GITHUB_OUTPUT

  check:
    needs: deploy
    runs-on: ubuntu-22.04

    steps:
      - name: "애플리케이션 서버 정상 동작 여부 점검"
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://${{ secrets.SERVER_HOST }}:${{ needs.deploy.outputs.active_port }}/actuator/health
          max-attempts: 5
          retry-delay: 5s
